### ISSUE TITLE
Préparation de l'environnement #2

### ISSUE THREAD

**Issue by mednajjar** [mednajjar/projet-comp#1]
Préparer le terrain pour un flux de travail Organizer, un code réutilisable et des tâches automatisées

- [x] git clone /lien Repository/ ou Fork
- [x] npm install /packages/
- [x] Watching concatenation Préfixage avec NPM Scripts
- [x] Compression du CSS et Javascript avec NPM Scripts

**Comment by mednajjar** [comment]
J'ai terminé toutes les étapes d'installation de l'environnement, maintenant je doit faire un push pour me donner votre feedback.

**Comment by youssefbm** [comment]
mettez le dossier img dans le dossier dist
